networks:
  simple_dictionary_network:
    external: true

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/simple_dictionary_api
      - ./_docker/nginx/conf.d/app.local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: project_nginx
    networks:
      - simple_dictionary_network
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile.dev
    volumes:
      - ./:/var/www/simple_dictionary_api
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: simple-dictionary
      MYSQL_ROOT_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
    container_name: app
    networks:
        - simple_dictionary_network
  db:
    image: mysql:8.1
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: simple-dictionary
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db
    networks:
        - simple_dictionary_network
